{
 "title": "mluvii",
 "tags": [
  "prometheus-net",
  "net",
  "prometheus",
  ".net",
  ".net core",
  "mluvii"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "jobs",
    "label": "jobs",
    "query": "label_values(dotnet_total_memory_bytes, job)"
   },
   {
    "name": "instances",
    "label": "instances",
    "query": "label_values(dotnet_total_memory_bytes, instance)"
   },
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "GC collection count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(dotnet_collection_count_total{job =~ \"$jobs\",instance =~ \"$instances\"}[$interval])",
     "legendFormat": "Generation-{{generation}} {{job}} {{instance}}"
    }
   ]
  },
  {
   "title": "Total known allocated memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes{job =~ \"$jobs\",instance =~ \"$instances\"} /1024/1024",
     "legendFormat": "{{job}} {{instance}}"
    }
   ]
  },
  {
   "title": "Start time of the process",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{job =~ \"$jobs\",instance =~ \"$instances\"} * 1000",
     "legendFormat": "{{job}} {{instance}}"
    }
   ]
  },
  {
   "title": "Thread pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dotnet_threadpool_worker_busy{job =~ \"$jobs\",instance =~ \"$instances\"}",
     "legendFormat": "worker_busy {{job}} {{instance}}"
    },
    {
     "expr": "dotnet_threadpool_worker_min{job =~ \"$jobs\",instance =~ \"$instances\"}",
     "legendFormat": "worker_min {{job}} {{instance}}"
    },
    {
     "expr": "dotnet_threadpool_completion_port_busy{job =~ \"$jobs\",instance =~ \"$instances\"}",
     "legendFormat": "completion_port_busy {{job}} {{instance}}"
    },
    {
     "expr": "dotnet_threadpool_completion_port_min{job =~ \"$jobs\",instance =~ \"$instances\"}",
     "legendFormat": "completion_port_min {{job}} {{instance}}"
    }
   ]
  },
  {
   "title": "Process working set",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_working_set_bytes{job =~ \"$jobs\",instance =~ \"$instances\"} /1024/1024",
     "legendFormat": "{{job}} {{instance}}"
    }
   ]
  },
  {
   "title": "Total number of threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_num_threads{job =~ \"$jobs\",instance =~ \"$instances\"}",
     "legendFormat": "{{job}} {{instance}}"
    }
   ]
  },
  {
   "title": "Number of open handles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_handles{job =~ \"$jobs\",instance =~ \"$instances\"}",
     "legendFormat": "{{job}} {{instance}}"
    }
   ]
  },
  {
   "title": "Total number of timers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dotnet_timer_count{job =~ \"$jobs\",instance =~ \"$instances\"}",
     "legendFormat": "{{job}} {{instance}}"
    }
   ]
  }
 ]
}